#pragma once
#include "xlezautomation.h"

enum EXL_COL { COL_A,COL_B,COL_C,COL_D,COL_E,COL_F,COL_G,COL_H,COL_I,COL_J,COL_K,COL_L,COL_M,COL_N,COL_O,COL_P,COL_Q,COL_R,COL_S,COL_T,COL_U,COL_V,COL_W,COL_X ,COL_Y ,COL_Z
             ,COL_AA,COL_AB,COL_AC,COL_AD,COL_AE,COL_AF,COL_AG,COL_AH,COL_AI,COL_AJ,COL_AK,COL_AL,COL_AM,COL_AN,COL_AO,COL_AP,COL_AQ,COL_AR,COL_AS,COL_AT,COL_AU,COL_AV,COL_AW,COL_AX,COL_AY,COL_AZ
             ,COL_BA,COL_BB,COL_BC,COL_BD,COL_BE,COL_BF,COL_BG,COL_BH,COL_BI,COL_BJ,COL_BK,COL_BL,COL_BM,COL_BN,COL_BO,COL_BP,COL_BQ,COL_BR,COL_BS,COL_BT,COL_BU,COL_BV,COL_BW,COL_BX,COL_BY,COL_BZ
             ,COL_CA,COL_CB,COL_CC,COL_CD,COL_CE,COL_CF,COL_CG,COL_CH,COL_CI,COL_CJ,COL_CK,COL_CL,COL_CM,COL_CN,COL_CO,COL_CP,COL_CQ,COL_CR,COL_CS,COL_CT,COL_CU,COL_CV,COL_CW,COL_CX,COL_CY,COL_CZ
             ,COL_DA,COL_DB,COL_DC,COL_DD,COL_DE,COL_DF,COL_DG,COL_DH,COL_DI,COL_DJ,COL_DK,COL_DL,COL_DM,COL_DN,COL_DO,COL_DP,COL_DQ,COL_DR,COL_DS,COL_DT,COL_DU,COL_DV,COL_DW,COL_DX,COL_DY,COL_DZ
             ,COL_EA,COL_EB,COL_EC,COL_ED,COL_EE,COL_EF,COL_EG,COL_EH,COL_EI,COL_EJ,COL_EK,COL_EL,COL_EM,COL_EN,COL_EO,COL_EP,COL_EQ,COL_ER,COL_ES,COL_ET,COL_EU,COL_EV,COL_EW,COL_EX,COL_EY,COL_EZ
             ,COL_FA,COL_FB,COL_FC,COL_FD,COL_FE,COL_FF,COL_FG,COL_FH,COL_FI,COL_FJ,COL_FK,COL_FL,COL_FM,COL_FN,COL_FO,COL_FP,COL_FQ,COL_FR,COL_FS,COL_FT,COL_FU,COL_FV,COL_FW,COL_FX,COL_FY,COL_FZ
             ,COL_GA,COL_GB,COL_GC,COL_GD,COL_GE,COL_GF,COL_GG,COL_GH,COL_GI,COL_GJ,COL_GK,COL_GL,COL_GM,COL_GN,COL_GO,COL_GP,COL_GQ,COL_GR,COL_GS,COL_GT,COL_GU,COL_GV,COL_GW,COL_GX,COL_GY,COL_GZ
             ,COL_HA,COL_HB,COL_HC,COL_HD,COL_HE,COL_HF,COL_HG,COL_HH,COL_HI,COL_HJ,COL_HK,COL_HL,COL_HM,COL_HN,COL_HO,COL_HP,COL_HQ,COL_HR,COL_HS,COL_HT,COL_HU,COL_HV,COL_HW,COL_HX,COL_HY,COL_HZ
             ,COL_IA,COL_IB,COL_IC,COL_ID,COL_IE,COL_IF,COL_IG,COL_IH,COL_II,COL_IJ,COL_IK,COL_IL,COL_IM,COL_IN,COL_IO,COL_IP,COL_IQ,COL_IR,COL_IS,COL_IT,COL_IU,COL_IV,COL_IW,COL_IX,COL_IY,COL_IZ
             ,COL_JA,COL_JB,COL_JC,COL_JD,COL_JE,COL_JF,COL_JG,COL_JH,COL_JI,COL_JJ,COL_JK,COL_JL,COL_JM,COL_JN,COL_JO,COL_JP,COL_JQ,COL_JR,COL_JS,COL_JT,COL_JU,COL_JV,COL_JW,COL_JX,COL_JY,COL_JZ
             ,COL_KA,COL_KB,COL_KC,COL_KD,COL_KE,COL_KF,COL_KG,COL_KH,COL_KI,COL_KJ,COL_KK,COL_KL,COL_KM,COL_KN,COL_KO,COL_KP,COL_KQ,COL_KR,COL_KS,COL_KT,COL_KU,COL_KV,COL_KW,COL_KX,COL_KY,COL_KZ
             ,COL_LA,COL_LB,COL_LC,COL_LD,COL_LE,COL_LF,COL_LG,COL_LH,COL_LI,COL_LJ,COL_LK,COL_LL,COL_LM,COL_LN,COL_LO,COL_LP,COL_LQ,COL_LR,COL_LS,COL_LT,COL_LU,COL_LV,COL_LW,COL_LX,COL_LY,COL_LZ
             ,COL_MA,COL_MB,COL_MC,COL_MD,COL_ME,COL_MF,COL_MG,COL_MH,COL_MI,COL_MJ,COL_MK,COL_ML,COL_MM,COL_MN,COL_MO,COL_MP,COL_MQ,COL_MR,COL_MS,COL_MT,COL_MU,COL_MV,COL_MW,COL_MX,COL_MY,COL_MZ
             ,COL_NA,COL_NB,COL_NC,COL_ND,COL_NE,COL_NF,COL_NG,COL_NH,COL_NI,COL_NJ,COL_NK,COL_NL,COL_NM,COL_NN,COL_NO,COL_NP,COL_NQ,COL_NR,COL_NS,COL_NT,COL_NU,COL_NV,COL_NW,COL_NX,COL_NY,COL_NZ
             ,COL_OA,COL_OB,COL_OC,COL_OD,COL_OE,COL_OF,COL_OG,COL_OH,COL_OI,COL_OJ,COL_OK,COL_OL,COL_OM,COL_ON,COL_OO,COL_OP,COL_OQ,COL_OR,COL_OS,COL_OT,COL_OU,COL_OV,COL_OW,COL_OX,COL_OY,COL_OZ
			 ,COL_PA,COL_PB,COL_PC,COL_PD,COL_PE,COL_PF,COL_PG,COL_PH,COL_PI,COL_PJ,COL_PK,COL_PL,COL_PM,COL_PN,COL_PO,COL_PP,COL_PQ,COL_PR,COL_PS,COL_PT,COL_PU,COL_PV,COL_PW,COL_PX,COL_PY,COL_PZ
			 ,COL_QA,COL_QB,COL_QC,COL_QD,COL_QE,COL_QF,COL_QG,COL_QH,COL_QI,COL_QJ,COL_QK,COL_QL,COL_QM,COL_QN,COL_QO,COL_QP,COL_QQ,COL_QR,COL_QS,COL_QT,COL_QU,COL_QV,COL_QW,COL_QX,COL_QY,COL_QZ
			 ,COL_RA,COL_RB,COL_RC,COL_RD,COL_RE,COL_RF,COL_RG,COL_RH,COL_RI,COL_RJ,COL_RK,COL_RL,COL_RM,COL_RN,COL_RO,COL_RP,COL_RQ,COL_RR,COL_RS,COL_RT,COL_RU,COL_RV,COL_RW,COL_RX,COL_RY,COL_RZ
			 ,COL_SA,COL_SB,COL_SC,COL_SD,COL_SE,COL_SF,COL_SG,COL_SH,COL_SI,COL_SJ,COL_SK,COL_SL,COL_SM,COL_SN,COL_SO,COL_SP,COL_SQ,COL_SR,COL_SS,COL_ST,COL_SU,COL_SV,COL_SW,COL_SX,COL_SY,COL_SZ
			 ,COL_TA,COL_TB,COL_TC,COL_TD,COL_TE,COL_TF,COL_TG,COL_TH,COL_TI,COL_TJ,COL_TK,COL_TL,COL_TM,COL_TN,COL_TO,COL_TP,COL_TQ,COL_TR,COL_TS,COL_TT,COL_TU,COL_TV,COL_TW,COL_TX,COL_TY,COL_TZ
			 ,COL_UA,COL_UB,COL_UC,COL_UD,COL_UE,COL_UF,COL_UG,COL_UH,COL_UI,COL_UJ,COL_UK,COL_UL,COL_UM,COL_UN,COL_UO,COL_UP,COL_UQ,COL_UR,COL_US,COL_UT,COL_UU,COL_UV,COL_UW,COL_UX,COL_UY,COL_UZ
			 ,COL_VA,COL_VB,COL_VC,COL_VD,COL_VE,COL_VF,COL_VG,COL_VH,COL_VI,COL_VJ,COL_VK,COL_VL,COL_VM,COL_VN,COL_VO,COL_VP,COL_VQ,COL_VR,COL_VS,COL_VT,COL_VU,COL_VV,COL_VW,COL_VX,COL_VY,COL_VZ
			 ,COL_WA,COL_WB,COL_WC,COL_WD,COL_WE,COL_WF,COL_WG,COL_WH,COL_WI,COL_WJ,COL_WK,COL_WL,COL_WM,COL_WN,COL_WO,COL_WP,COL_WQ,COL_WR,COL_WS,COL_WT,COL_WU,COL_WV,COL_WW,COL_WX,COL_WY,COL_WZ
			 ,COL_XA,COL_XB,COL_XC,COL_XD,COL_XE,COL_XF,COL_XG,COL_XH,COL_XI,COL_XJ,COL_XK,COL_XL,COL_XM,COL_XN,COL_XO,COL_XP,COL_XQ,COL_XR,COL_XS,COL_XT,COL_XU,COL_XV,COL_XW,COL_XX,COL_XY,COL_XZ
			 ,COL_YA,COL_YB,COL_YC,COL_YD,COL_YE,COL_YF,COL_YG,COL_YH,COL_YI,COL_YJ,COL_YK,COL_YL,COL_YM,COL_YN,COL_YO,COL_YP,COL_YQ,COL_YR,COL_YS,COL_YT,COL_YU,COL_YV,COL_YW,COL_YX,COL_YY,COL_YZ
			 ,COL_ZA,COL_ZB,COL_ZC,COL_ZD,COL_ZE,COL_ZF,COL_ZG,COL_ZH,COL_ZI,COL_ZJ,COL_ZK,COL_ZL,COL_ZM,COL_ZN,COL_ZO,COL_ZP,COL_ZQ,COL_ZR,COL_ZS,COL_ZT,COL_ZU,COL_ZV,COL_ZW,COL_ZX,COL_ZY,COL_ZZ
};

class CXLEzAutoStandard :
	public CXLEzAutomation
{


public:
	CXLEzAutoStandard(void);
	CXLEzAutoStandard(BOOL bVisible);
	~CXLEzAutoStandard(void);

	//BOOL SetCellValueStd();
	//CString GetCellValueStd();

	void SetCurrentDirStd(CString dir);
	CString GetCurrentDirStd();

protected:
	CXLEzAutomation *m_pSubClass;
	CString m_Current_Dir;
};


class CExcelPos
{
public :
	EXL_COL col;
	int     row;
};